[book]
title = "Crypto 101: Đi Săn"
description = "Kĩ năng săn kèo trong thế giới Crypto"
authors = ["SkywireX team"]
language = "vi"
src = "src"

[output.html]
git-repository-url = "https://github.com/skywirex/c101.skywirex.com"
default-theme = "light"
additional-css = ["theme/css/custom.css"]
