[book]
title = "Crypto 101: Thợ Săn"
description = "Kĩ năng săn kèo trong thế giới Crypto"
authors = ["SkywireX team"]
language = "vi"
multilingual = false
src = "src"
git-repository-url = ""
git-repository-icon = "fa-github"

[output.html]
git-repository-url = ""
git-repository-icon = "fa-github"
default-theme = "light"